# Generated by Django 4.2.3 on 2023-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
