# Generated by Django 4.2.3 on 2023-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_cart_alter_cart_items_alter_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, default=1, related_name='carts', to='cart.cartitem'),
        ),
    ]
