# Generated by Django 4.2.3 on 2023-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
